<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordRequired</name>
   <tag></tag>
   <elementGuidId>586553f0-dd1d-4b9b-89b1-35e2ca8bd71c</elementGuidId>
   <imagePath>Screenshots/Targets/Page_OrangeHRM/passwordRequired.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_OrangeHRM/passwordRequired.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']/parent::div/following-sibling::span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>176cb446-106a-4364-a054-624a6674a578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1702633210436</value>
      <webElementGuid>e345be3a-7d4a-472b-9fdc-bdd4149eea21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>f82eb032-2595-457d-bbe3-2673108906ce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
