<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgotPassword</name>
   <tag></tag>
   <elementGuidId>fa47805f-de03-4a62-ae90-481963067bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.orangehrm-login-forgot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5186161f-15f6-4ba3-adf9-54292b70ee7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1702620068805</value>
      <webElementGuid>1fb3e816-c861-4fb4-ad2e-fee201c688a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
